name: sudoku_core
description: A sample command-line application.
version: 1.0.1
repository: https://github.com/MohitSG96/sudoku_core_dart
# repository: https://github.com/my_org/my_repo

environment:
    sdk: ^3.10.3

# Add regular dependencies here.
dependencies:
    path: ^1.9.0

dev_dependencies:
    lints: ^6.0.0
    test: ^1.25.6
